# Generated by Django 2.2.7 on 2019-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTable',
            new_name='HariSh',
        ),
    ]
